# App
name = "ImNotes"
comment = "ImExample is a simple Dear ImGui application example"
version = "0.4.0"
website = "https://github.com/Patitotective/ImTemplate"
authors = ["Patitotective <https://github.com/Patitotective>", "Cristobal <mailto:cristobalriaga@gmail.com>", "Omar Cornut <https://github.com/ocornut>", "Beef, Yard, Rika",  "and the Nim community :]", "Inu147"]
categories = ["Utility"]

# AppImage
ghRepo = "Patitotective/ImTemplate"

stylePath = "assets/style.toml"
iconPath = "assets/icon.png"
svgIconPath = "assets/icon.svg"
iconFontPath = "assets/forkawesome-webfont.ttf"
fontPath = "assets/ProggyVector Regular.ttf" # Other options are Roboto-Regular.ttf, Cousine-Regular.ttf or Karla-Regular.ttf
fontSize = 16.0

# Window
minSize = [300, 300] # Width, height

# Settings for the preferences window
[settings.maxNotes]
display = "Max notes per page"
type = "spin" # Input int
default = 4
step = 1
step_fast = 1
min = 1
max = 6
flags = "None" # See https://nimgl.dev/docs/imgui.html#ImGuiInputTextFlags
